# Generated by Django 4.1.5 on 2023-01-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
                ('current_balance', models.FloatField()),
                ('start_balance', models.FloatField()),
                ('leverage', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SignalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0)),
                ('price_change', models.FloatField(default=0)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.signal')),
            ],
        ),
    ]
