# Generated by Django 4.1.5 on 2023-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='signalresult',
            name='source',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
